//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Entries.Services.wcf_Banco {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelBase", Namespace="http://schemas.datacontract.org/2004/07/HLP.Base.ClassesBases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Financeiro.BancoModel))]
    public partial class modelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<HLP.Entries.Services.wcf_Banco.PesquisaPadraoModelContract> lcamposSqlNotNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Entries.Services.wcf_Banco.statusModel statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<HLP.Entries.Services.wcf_Banco.PesquisaPadraoModelContract> lcamposSqlNotNull {
            get {
                return this.lcamposSqlNotNullField;
            }
            set {
                if ((object.ReferenceEquals(this.lcamposSqlNotNullField, value) != true)) {
                    this.lcamposSqlNotNullField = value;
                    this.RaisePropertyChanged("lcamposSqlNotNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Entries.Services.wcf_Banco.statusModel status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PesquisaPadraoModelContract", Namespace="http://schemas.datacontract.org/2004/07/HLP.Base.ClassesBases")]
    [System.SerializableAttribute()]
    public partial class PesquisaPadraoModelContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CHARACTER_MAXIMUM_LENGTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLUMN_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IS_NULLABLEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHARACTER_MAXIMUM_LENGTH {
            get {
                return this.CHARACTER_MAXIMUM_LENGTHField;
            }
            set {
                if ((this.CHARACTER_MAXIMUM_LENGTHField.Equals(value) != true)) {
                    this.CHARACTER_MAXIMUM_LENGTHField = value;
                    this.RaisePropertyChanged("CHARACTER_MAXIMUM_LENGTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLUMN_NAME {
            get {
                return this.COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COLUMN_NAMEField, value) != true)) {
                    this.COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("COLUMN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_TYPEField, value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IS_NULLABLE {
            get {
                return this.IS_NULLABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.IS_NULLABLEField, value) != true)) {
                    this.IS_NULLABLEField = value;
                    this.RaisePropertyChanged("IS_NULLABLE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="statusModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Base.EnumsBases")]
    public enum statusModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nenhum = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        criado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        alterado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        excluido = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf_Banco.Iwcf_Banco")]
    public interface Iwcf_Banco {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Save", ReplyAction="http://tempuri.org/Iwcf_Banco/SaveResponse")]
        int Save(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Save", ReplyAction="http://tempuri.org/Iwcf_Banco/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/GetObjeto", ReplyAction="http://tempuri.org/Iwcf_Banco/GetObjetoResponse")]
        HLP.Entries.Model.Models.Financeiro.BancoModel GetObjeto(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/GetObjeto", ReplyAction="http://tempuri.org/Iwcf_Banco/GetObjetoResponse")]
        System.Threading.Tasks.Task<HLP.Entries.Model.Models.Financeiro.BancoModel> GetObjetoAsync(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Delete", ReplyAction="http://tempuri.org/Iwcf_Banco/DeleteResponse")]
        bool Delete(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Delete", ReplyAction="http://tempuri.org/Iwcf_Banco/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Copy", ReplyAction="http://tempuri.org/Iwcf_Banco/CopyResponse")]
        int Copy(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Copy", ReplyAction="http://tempuri.org/Iwcf_Banco/CopyResponse")]
        System.Threading.Tasks.Task<int> CopyAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/GetHierarquia", ReplyAction="http://tempuri.org/Iwcf_Banco/GetHierarquiaResponse")]
        HLP.Components.Model.Models.modelToTreeView GetHierarquia(int idBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/GetHierarquia", ReplyAction="http://tempuri.org/Iwcf_Banco/GetHierarquiaResponse")]
        System.Threading.Tasks.Task<HLP.Components.Model.Models.modelToTreeView> GetHierarquiaAsync(int idBanco);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iwcf_BancoChannel : HLP.Entries.Services.wcf_Banco.Iwcf_Banco, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iwcf_BancoClient : System.ServiceModel.ClientBase<HLP.Entries.Services.wcf_Banco.Iwcf_Banco>, HLP.Entries.Services.wcf_Banco.Iwcf_Banco {
        
        public Iwcf_BancoClient() {
        }
        
        public Iwcf_BancoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iwcf_BancoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_BancoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_BancoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Save(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.Save(Objeto);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.SaveAsync(Objeto);
        }
        
        public HLP.Entries.Model.Models.Financeiro.BancoModel GetObjeto(int idObjeto) {
            return base.Channel.GetObjeto(idObjeto);
        }
        
        public System.Threading.Tasks.Task<HLP.Entries.Model.Models.Financeiro.BancoModel> GetObjetoAsync(int idObjeto) {
            return base.Channel.GetObjetoAsync(idObjeto);
        }
        
        public bool Delete(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.Delete(Objeto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.DeleteAsync(Objeto);
        }
        
        public int Copy(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.Copy(Objeto);
        }
        
        public System.Threading.Tasks.Task<int> CopyAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.CopyAsync(Objeto);
        }
        
        public HLP.Components.Model.Models.modelToTreeView GetHierarquia(int idBanco) {
            return base.Channel.GetHierarquia(idBanco);
        }
        
        public System.Threading.Tasks.Task<HLP.Components.Model.Models.modelToTreeView> GetHierarquiaAsync(int idBanco) {
            return base.Channel.GetHierarquiaAsync(idBanco);
        }
    }
}
