//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Entries.Services.wcf_Banco {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelBase", Namespace="http://schemas.datacontract.org/2004/07/HLP.Base.ClassesBases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Services.wcf_Banco.DocumentosModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Services.wcf_Banco.modelComum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Financeiro.BancoModel))]
    public partial class modelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentosModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    public partial class DocumentosModel : HLP.Entries.Services.wcf_Banco.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xExtensaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xNameTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xPathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDocumento {
            get {
                return this.idDocumentoField;
            }
            set {
                if ((this.idDocumentoField.Equals(value) != true)) {
                    this.idDocumentoField = value;
                    this.RaisePropertyChanged("idDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPk {
            get {
                return this.idPkField;
            }
            set {
                if ((this.idPkField.Equals(value) != true)) {
                    this.idPkField = value;
                    this.RaisePropertyChanged("idPk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xDocumento {
            get {
                return this.xDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.xDocumentoField, value) != true)) {
                    this.xDocumentoField = value;
                    this.RaisePropertyChanged("xDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xExtensao {
            get {
                return this.xExtensaoField;
            }
            set {
                if ((object.ReferenceEquals(this.xExtensaoField, value) != true)) {
                    this.xExtensaoField = value;
                    this.RaisePropertyChanged("xExtensao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xNameTable {
            get {
                return this.xNameTableField;
            }
            set {
                if ((object.ReferenceEquals(this.xNameTableField, value) != true)) {
                    this.xNameTableField = value;
                    this.RaisePropertyChanged("xNameTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xPath {
            get {
                return this.xPathField;
            }
            set {
                if ((object.ReferenceEquals(this.xPathField, value) != true)) {
                    this.xPathField = value;
                    this.RaisePropertyChanged("xPath");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelComum", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Financeiro.BancoModel))]
    public partial class modelComum : HLP.Entries.Services.wcf_Banco.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<HLP.Entries.Services.wcf_Banco.DocumentosModel> lDocumentosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<HLP.Entries.Services.wcf_Banco.DocumentosModel> lDocumentos {
            get {
                return this.lDocumentosField;
            }
            set {
                if ((object.ReferenceEquals(this.lDocumentosField, value) != true)) {
                    this.lDocumentosField = value;
                    this.RaisePropertyChanged("lDocumentos");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf_Banco.Iwcf_Banco")]
    public interface Iwcf_Banco {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Save", ReplyAction="http://tempuri.org/Iwcf_Banco/SaveResponse")]
        int Save(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Save", ReplyAction="http://tempuri.org/Iwcf_Banco/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/GetObjeto", ReplyAction="http://tempuri.org/Iwcf_Banco/GetObjetoResponse")]
        HLP.Entries.Model.Models.Financeiro.BancoModel GetObjeto(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/GetObjeto", ReplyAction="http://tempuri.org/Iwcf_Banco/GetObjetoResponse")]
        System.Threading.Tasks.Task<HLP.Entries.Model.Models.Financeiro.BancoModel> GetObjetoAsync(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Delete", ReplyAction="http://tempuri.org/Iwcf_Banco/DeleteResponse")]
        bool Delete(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Delete", ReplyAction="http://tempuri.org/Iwcf_Banco/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Copy", ReplyAction="http://tempuri.org/Iwcf_Banco/CopyResponse")]
        int Copy(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/Copy", ReplyAction="http://tempuri.org/Iwcf_Banco/CopyResponse")]
        System.Threading.Tasks.Task<int> CopyAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/GetHierarquia", ReplyAction="http://tempuri.org/Iwcf_Banco/GetHierarquiaResponse")]
        HLP.Components.Model.Models.modelToTreeView GetHierarquia(int idBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_Banco/GetHierarquia", ReplyAction="http://tempuri.org/Iwcf_Banco/GetHierarquiaResponse")]
        System.Threading.Tasks.Task<HLP.Components.Model.Models.modelToTreeView> GetHierarquiaAsync(int idBanco);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iwcf_BancoChannel : HLP.Entries.Services.wcf_Banco.Iwcf_Banco, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iwcf_BancoClient : System.ServiceModel.ClientBase<HLP.Entries.Services.wcf_Banco.Iwcf_Banco>, HLP.Entries.Services.wcf_Banco.Iwcf_Banco {
        
        public Iwcf_BancoClient() {
        }
        
        public Iwcf_BancoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iwcf_BancoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_BancoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_BancoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Save(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.Save(Objeto);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.SaveAsync(Objeto);
        }
        
        public HLP.Entries.Model.Models.Financeiro.BancoModel GetObjeto(int idObjeto) {
            return base.Channel.GetObjeto(idObjeto);
        }
        
        public System.Threading.Tasks.Task<HLP.Entries.Model.Models.Financeiro.BancoModel> GetObjetoAsync(int idObjeto) {
            return base.Channel.GetObjetoAsync(idObjeto);
        }
        
        public bool Delete(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.Delete(Objeto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.DeleteAsync(Objeto);
        }
        
        public int Copy(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.Copy(Objeto);
        }
        
        public System.Threading.Tasks.Task<int> CopyAsync(HLP.Entries.Model.Models.Financeiro.BancoModel Objeto) {
            return base.Channel.CopyAsync(Objeto);
        }
        
        public HLP.Components.Model.Models.modelToTreeView GetHierarquia(int idBanco) {
            return base.Channel.GetHierarquia(idBanco);
        }
        
        public System.Threading.Tasks.Task<HLP.Components.Model.Models.modelToTreeView> GetHierarquiaAsync(int idBanco) {
            return base.Channel.GetHierarquiaAsync(idBanco);
        }
    }
}
