//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Entries.ViewModel.Condicao_PagamentoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelBase", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.Condicao_pagamentoModel))]
    public partial class modelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Entries.ViewModel.Condicao_PagamentoService.PesquisaPadraoModelContract[] lcamposSqlNotNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Entries.ViewModel.Condicao_PagamentoService.statusModel statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Entries.ViewModel.Condicao_PagamentoService.PesquisaPadraoModelContract[] lcamposSqlNotNull {
            get {
                return this.lcamposSqlNotNullField;
            }
            set {
                if ((object.ReferenceEquals(this.lcamposSqlNotNullField, value) != true)) {
                    this.lcamposSqlNotNullField = value;
                    this.RaisePropertyChanged("lcamposSqlNotNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Entries.ViewModel.Condicao_PagamentoService.statusModel status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PesquisaPadraoModelContract", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Components")]
    [System.SerializableAttribute()]
    public partial class PesquisaPadraoModelContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLUMN_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLUMN_NAME {
            get {
                return this.COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COLUMN_NAMEField, value) != true)) {
                    this.COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("COLUMN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_TYPEField, value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="statusModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Resources.RecursosBases")]
    public enum statusModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nenhum = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        criado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        alterado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        excluido = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Condicao_PagamentoService.IserviceCondicao_Pagamento")]
    public interface IserviceCondicao_Pagamento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCondicao_Pagamento/getCondicao_pagamento", ReplyAction="http://tempuri.org/IserviceCondicao_Pagamento/getCondicao_pagamentoResponse")]
        HLP.Entries.Model.Models.Gerais.Condicao_pagamentoModel getCondicao_pagamento(int idCondicao_pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCondicao_Pagamento/getCondicao_pagamento", ReplyAction="http://tempuri.org/IserviceCondicao_Pagamento/getCondicao_pagamentoResponse")]
        System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Condicao_pagamentoModel> getCondicao_pagamentoAsync(int idCondicao_pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCondicao_Pagamento/saveCondicao_pagamento", ReplyAction="http://tempuri.org/IserviceCondicao_Pagamento/saveCondicao_pagamentoResponse")]
        int saveCondicao_pagamento(HLP.Entries.Model.Models.Gerais.Condicao_pagamentoModel objCondicao_pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCondicao_Pagamento/saveCondicao_pagamento", ReplyAction="http://tempuri.org/IserviceCondicao_Pagamento/saveCondicao_pagamentoResponse")]
        System.Threading.Tasks.Task<int> saveCondicao_pagamentoAsync(HLP.Entries.Model.Models.Gerais.Condicao_pagamentoModel objCondicao_pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCondicao_Pagamento/deleteCondicao_pagamento", ReplyAction="http://tempuri.org/IserviceCondicao_Pagamento/deleteCondicao_pagamentoResponse")]
        bool deleteCondicao_pagamento(int idCondicao_pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCondicao_Pagamento/deleteCondicao_pagamento", ReplyAction="http://tempuri.org/IserviceCondicao_Pagamento/deleteCondicao_pagamentoResponse")]
        System.Threading.Tasks.Task<bool> deleteCondicao_pagamentoAsync(int idCondicao_pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCondicao_Pagamento/copyCondicao_pagamento", ReplyAction="http://tempuri.org/IserviceCondicao_Pagamento/copyCondicao_pagamentoResponse")]
        int copyCondicao_pagamento(int idCondicao_pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCondicao_Pagamento/copyCondicao_pagamento", ReplyAction="http://tempuri.org/IserviceCondicao_Pagamento/copyCondicao_pagamentoResponse")]
        System.Threading.Tasks.Task<int> copyCondicao_pagamentoAsync(int idCondicao_pagamento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IserviceCondicao_PagamentoChannel : HLP.Entries.ViewModel.Condicao_PagamentoService.IserviceCondicao_Pagamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IserviceCondicao_PagamentoClient : System.ServiceModel.ClientBase<HLP.Entries.ViewModel.Condicao_PagamentoService.IserviceCondicao_Pagamento>, HLP.Entries.ViewModel.Condicao_PagamentoService.IserviceCondicao_Pagamento {
        
        public IserviceCondicao_PagamentoClient() {
        }
        
        public IserviceCondicao_PagamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IserviceCondicao_PagamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceCondicao_PagamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceCondicao_PagamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HLP.Entries.Model.Models.Gerais.Condicao_pagamentoModel getCondicao_pagamento(int idCondicao_pagamento) {
            return base.Channel.getCondicao_pagamento(idCondicao_pagamento);
        }
        
        public System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Condicao_pagamentoModel> getCondicao_pagamentoAsync(int idCondicao_pagamento) {
            return base.Channel.getCondicao_pagamentoAsync(idCondicao_pagamento);
        }
        
        public int saveCondicao_pagamento(HLP.Entries.Model.Models.Gerais.Condicao_pagamentoModel objCondicao_pagamento) {
            return base.Channel.saveCondicao_pagamento(objCondicao_pagamento);
        }
        
        public System.Threading.Tasks.Task<int> saveCondicao_pagamentoAsync(HLP.Entries.Model.Models.Gerais.Condicao_pagamentoModel objCondicao_pagamento) {
            return base.Channel.saveCondicao_pagamentoAsync(objCondicao_pagamento);
        }
        
        public bool deleteCondicao_pagamento(int idCondicao_pagamento) {
            return base.Channel.deleteCondicao_pagamento(idCondicao_pagamento);
        }
        
        public System.Threading.Tasks.Task<bool> deleteCondicao_pagamentoAsync(int idCondicao_pagamento) {
            return base.Channel.deleteCondicao_pagamentoAsync(idCondicao_pagamento);
        }
        
        public int copyCondicao_pagamento(int idCondicao_pagamento) {
            return base.Channel.copyCondicao_pagamento(idCondicao_pagamento);
        }
        
        public System.Threading.Tasks.Task<int> copyCondicao_pagamentoAsync(int idCondicao_pagamento) {
            return base.Channel.copyCondicao_pagamentoAsync(idCondicao_pagamento);
        }
    }
}
