//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Comum.Facade.CodigoIcmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelBase", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Comum.Facade.CodigoIcmsService.Codigo_IcmsModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel))]
    public partial class modelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.CodigoIcmsService.PesquisaPadraoModelContract[] lcamposSqlNotNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.CodigoIcmsService.statusModel statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.CodigoIcmsService.PesquisaPadraoModelContract[] lcamposSqlNotNull {
            get {
                return this.lcamposSqlNotNullField;
            }
            set {
                if ((object.ReferenceEquals(this.lcamposSqlNotNullField, value) != true)) {
                    this.lcamposSqlNotNullField = value;
                    this.RaisePropertyChanged("lcamposSqlNotNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.CodigoIcmsService.statusModel status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Codigo_IcmsModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Entries.Model.Models.Fiscal")]
    [System.SerializableAttribute()]
    public partial class Codigo_IcmsModel : HLP.Comum.Facade.CodigoIcmsService.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCSTIcmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCodigoIcmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCodigoIcmsPaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pIcmsEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pIcmsInternaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pIcmsNaoContribruinteForaEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pIcmsSubstituicaoTributariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pMvaSubstituicaoTributariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vCoeficienteIcmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xFundamLegalCodTribField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCSTIcms {
            get {
                return this.idCSTIcmsField;
            }
            set {
                if ((this.idCSTIcmsField.Equals(value) != true)) {
                    this.idCSTIcmsField = value;
                    this.RaisePropertyChanged("idCSTIcms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCodigoIcms {
            get {
                return this.idCodigoIcmsField;
            }
            set {
                if ((this.idCodigoIcmsField.Equals(value) != true)) {
                    this.idCodigoIcmsField = value;
                    this.RaisePropertyChanged("idCodigoIcms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCodigoIcmsPai {
            get {
                return this.idCodigoIcmsPaiField;
            }
            set {
                if ((this.idCodigoIcmsPaiField.Equals(value) != true)) {
                    this.idCodigoIcmsPaiField = value;
                    this.RaisePropertyChanged("idCodigoIcmsPai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUf {
            get {
                return this.idUfField;
            }
            set {
                if ((this.idUfField.Equals(value) != true)) {
                    this.idUfField = value;
                    this.RaisePropertyChanged("idUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pIcmsEstado {
            get {
                return this.pIcmsEstadoField;
            }
            set {
                if ((this.pIcmsEstadoField.Equals(value) != true)) {
                    this.pIcmsEstadoField = value;
                    this.RaisePropertyChanged("pIcmsEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pIcmsInterna {
            get {
                return this.pIcmsInternaField;
            }
            set {
                if ((this.pIcmsInternaField.Equals(value) != true)) {
                    this.pIcmsInternaField = value;
                    this.RaisePropertyChanged("pIcmsInterna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pIcmsNaoContribruinteForaEstado {
            get {
                return this.pIcmsNaoContribruinteForaEstadoField;
            }
            set {
                if ((this.pIcmsNaoContribruinteForaEstadoField.Equals(value) != true)) {
                    this.pIcmsNaoContribruinteForaEstadoField = value;
                    this.RaisePropertyChanged("pIcmsNaoContribruinteForaEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pIcmsSubstituicaoTributaria {
            get {
                return this.pIcmsSubstituicaoTributariaField;
            }
            set {
                if ((this.pIcmsSubstituicaoTributariaField.Equals(value) != true)) {
                    this.pIcmsSubstituicaoTributariaField = value;
                    this.RaisePropertyChanged("pIcmsSubstituicaoTributaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pMvaSubstituicaoTributaria {
            get {
                return this.pMvaSubstituicaoTributariaField;
            }
            set {
                if ((this.pMvaSubstituicaoTributariaField.Equals(value) != true)) {
                    this.pMvaSubstituicaoTributariaField = value;
                    this.RaisePropertyChanged("pMvaSubstituicaoTributaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vCoeficienteIcms {
            get {
                return this.vCoeficienteIcmsField;
            }
            set {
                if ((this.vCoeficienteIcmsField.Equals(value) != true)) {
                    this.vCoeficienteIcmsField = value;
                    this.RaisePropertyChanged("vCoeficienteIcms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xFundamLegalCodTrib {
            get {
                return this.xFundamLegalCodTribField;
            }
            set {
                if ((object.ReferenceEquals(this.xFundamLegalCodTribField, value) != true)) {
                    this.xFundamLegalCodTribField = value;
                    this.RaisePropertyChanged("xFundamLegalCodTrib");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Codigo_Icms_paiModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Entries.Model.Models.Fiscal")]
    [System.SerializableAttribute()]
    public partial class Codigo_Icms_paiModel : HLP.Comum.Facade.CodigoIcmsService.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cIcmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCodigoIcmsPaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.CodigoIcmsService.Codigo_IcmsModel[] lCodigo_IcmsModelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cIcms {
            get {
                return this.cIcmsField;
            }
            set {
                if ((this.cIcmsField.Equals(value) != true)) {
                    this.cIcmsField = value;
                    this.RaisePropertyChanged("cIcms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCodigoIcmsPai {
            get {
                return this.idCodigoIcmsPaiField;
            }
            set {
                if ((this.idCodigoIcmsPaiField.Equals(value) != true)) {
                    this.idCodigoIcmsPaiField = value;
                    this.RaisePropertyChanged("idCodigoIcmsPai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.CodigoIcmsService.Codigo_IcmsModel[] lCodigo_IcmsModel {
            get {
                return this.lCodigo_IcmsModelField;
            }
            set {
                if ((object.ReferenceEquals(this.lCodigo_IcmsModelField, value) != true)) {
                    this.lCodigo_IcmsModelField = value;
                    this.RaisePropertyChanged("lCodigo_IcmsModel");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PesquisaPadraoModelContract", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Components")]
    [System.SerializableAttribute()]
    public partial class PesquisaPadraoModelContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CHARACTER_MAXIMUM_LENGTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLUMN_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IS_NULLABLEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHARACTER_MAXIMUM_LENGTH {
            get {
                return this.CHARACTER_MAXIMUM_LENGTHField;
            }
            set {
                if ((this.CHARACTER_MAXIMUM_LENGTHField.Equals(value) != true)) {
                    this.CHARACTER_MAXIMUM_LENGTHField = value;
                    this.RaisePropertyChanged("CHARACTER_MAXIMUM_LENGTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLUMN_NAME {
            get {
                return this.COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COLUMN_NAMEField, value) != true)) {
                    this.COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("COLUMN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_TYPEField, value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IS_NULLABLE {
            get {
                return this.IS_NULLABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.IS_NULLABLEField, value) != true)) {
                    this.IS_NULLABLEField = value;
                    this.RaisePropertyChanged("IS_NULLABLE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="statusModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Resources.RecursosBases")]
    public enum statusModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nenhum = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        criado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        alterado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        excluido = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CodigoIcmsService.IserviceCodigoIcms")]
    public interface IserviceCodigoIcms {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCodigoIcms/Save", ReplyAction="http://tempuri.org/IserviceCodigoIcms/SaveResponse")]
        HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel Save(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCodigoIcms/Save", ReplyAction="http://tempuri.org/IserviceCodigoIcms/SaveResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel> SaveAsync(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCodigoIcms/GetObjeto", ReplyAction="http://tempuri.org/IserviceCodigoIcms/GetObjetoResponse")]
        HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel GetObjeto(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCodigoIcms/GetObjeto", ReplyAction="http://tempuri.org/IserviceCodigoIcms/GetObjetoResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel> GetObjetoAsync(int idObjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCodigoIcms/Delete", ReplyAction="http://tempuri.org/IserviceCodigoIcms/DeleteResponse")]
        bool Delete(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCodigoIcms/Delete", ReplyAction="http://tempuri.org/IserviceCodigoIcms/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCodigoIcms/Copy", ReplyAction="http://tempuri.org/IserviceCodigoIcms/CopyResponse")]
        HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel Copy(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceCodigoIcms/Copy", ReplyAction="http://tempuri.org/IserviceCodigoIcms/CopyResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel> CopyAsync(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IserviceCodigoIcmsChannel : HLP.Comum.Facade.CodigoIcmsService.IserviceCodigoIcms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IserviceCodigoIcmsClient : System.ServiceModel.ClientBase<HLP.Comum.Facade.CodigoIcmsService.IserviceCodigoIcms>, HLP.Comum.Facade.CodigoIcmsService.IserviceCodigoIcms {
        
        public IserviceCodigoIcmsClient() {
        }
        
        public IserviceCodigoIcmsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IserviceCodigoIcmsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceCodigoIcmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceCodigoIcmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel Save(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel) {
            return base.Channel.Save(objModel);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel> SaveAsync(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel) {
            return base.Channel.SaveAsync(objModel);
        }
        
        public HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel GetObjeto(int idObjeto) {
            return base.Channel.GetObjeto(idObjeto);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel> GetObjetoAsync(int idObjeto) {
            return base.Channel.GetObjetoAsync(idObjeto);
        }
        
        public bool Delete(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel) {
            return base.Channel.Delete(objModel);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel) {
            return base.Channel.DeleteAsync(objModel);
        }
        
        public HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel Copy(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel) {
            return base.Channel.Copy(objModel);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel> CopyAsync(HLP.Comum.Facade.CodigoIcmsService.Codigo_Icms_paiModel objModel) {
            return base.Channel.CopyAsync(objModel);
        }
    }
}
