//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Entries.Services.wcf_ParametroEmpresa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelBase", Namespace="http://schemas.datacontract.org/2004/07/HLP.Base.ClassesBases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Services.wcf_ParametroEmpresa.DocumentosModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Services.wcf_ParametroEmpresa.modelComum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_ComercialModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_ComprasModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_CustosModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_EstoqueModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_FinanceiroModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_FiscalModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_Ordem_ProducaoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_Cartao_PontoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.EmpresaParametrosModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Services.wcf_ParametroEmpresa.EnderecoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.EmpresaModel))]
    public partial class modelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentosModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    public partial class DocumentosModel : HLP.Entries.Services.wcf_ParametroEmpresa.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xExtensaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xNameTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xPathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDocumento {
            get {
                return this.idDocumentoField;
            }
            set {
                if ((this.idDocumentoField.Equals(value) != true)) {
                    this.idDocumentoField = value;
                    this.RaisePropertyChanged("idDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPk {
            get {
                return this.idPkField;
            }
            set {
                if ((this.idPkField.Equals(value) != true)) {
                    this.idPkField = value;
                    this.RaisePropertyChanged("idPk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xDocumento {
            get {
                return this.xDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.xDocumentoField, value) != true)) {
                    this.xDocumentoField = value;
                    this.RaisePropertyChanged("xDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xExtensao {
            get {
                return this.xExtensaoField;
            }
            set {
                if ((object.ReferenceEquals(this.xExtensaoField, value) != true)) {
                    this.xExtensaoField = value;
                    this.RaisePropertyChanged("xExtensao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xNameTable {
            get {
                return this.xNameTableField;
            }
            set {
                if ((object.ReferenceEquals(this.xNameTableField, value) != true)) {
                    this.xNameTableField = value;
                    this.RaisePropertyChanged("xNameTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xPath {
            get {
                return this.xPathField;
            }
            set {
                if ((object.ReferenceEquals(this.xPathField, value) != true)) {
                    this.xPathField = value;
                    this.RaisePropertyChanged("xPath");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelComum", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_ComercialModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_ComprasModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_CustosModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_EstoqueModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_FinanceiroModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_FiscalModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_Ordem_ProducaoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_Cartao_PontoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.EmpresaParametrosModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Services.wcf_ParametroEmpresa.EnderecoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.EmpresaModel))]
    public partial class modelComum : HLP.Entries.Services.wcf_ParametroEmpresa.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<HLP.Entries.Services.wcf_ParametroEmpresa.DocumentosModel> lDocumentosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<HLP.Entries.Services.wcf_ParametroEmpresa.DocumentosModel> lDocumentos {
            get {
                return this.lDocumentosField;
            }
            set {
                if ((object.ReferenceEquals(this.lDocumentosField, value) != true)) {
                    this.lDocumentosField = value;
                    this.RaisePropertyChanged("lDocumentos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Components.Model.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Services.wcf_ParametroEmpresa.modelBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_ComercialModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_ComprasModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_CustosModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_EstoqueModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_FinanceiroModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_FiscalModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_Ordem_ProducaoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Parametros.Parametro_Cartao_PontoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.EmpresaModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.EmpresaParametrosModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<HLP.Entries.Services.wcf_ParametroEmpresa.EnderecoModel>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Services.wcf_ParametroEmpresa.modelComum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<HLP.Entries.Services.wcf_ParametroEmpresa.DocumentosModel>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Services.wcf_ParametroEmpresa.DocumentosModel))]
    public partial class EnderecoModel : HLP.Entries.Services.wcf_ParametroEmpresa.modelComum {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bCanFindCepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idAgenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idClienteFornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idContatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idTransportadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object objCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stLogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> stPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stTipoEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xBairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xCEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xCaixaPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xNomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bCanFindCep {
            get {
                return this.bCanFindCepField;
            }
            set {
                if ((this.bCanFindCepField.Equals(value) != true)) {
                    this.bCanFindCepField = value;
                    this.RaisePropertyChanged("bCanFindCep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idAgencia {
            get {
                return this.idAgenciaField;
            }
            set {
                if ((this.idAgenciaField.Equals(value) != true)) {
                    this.idAgenciaField = value;
                    this.RaisePropertyChanged("idAgencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCidade {
            get {
                return this.idCidadeField;
            }
            set {
                if ((this.idCidadeField.Equals(value) != true)) {
                    this.idCidadeField = value;
                    this.RaisePropertyChanged("idCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idClienteFornecedor {
            get {
                return this.idClienteFornecedorField;
            }
            set {
                if ((this.idClienteFornecedorField.Equals(value) != true)) {
                    this.idClienteFornecedorField = value;
                    this.RaisePropertyChanged("idClienteFornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idContato {
            get {
                return this.idContatoField;
            }
            set {
                if ((this.idContatoField.Equals(value) != true)) {
                    this.idContatoField = value;
                    this.RaisePropertyChanged("idContato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idEndereco {
            get {
                return this.idEnderecoField;
            }
            set {
                if ((this.idEnderecoField.Equals(value) != true)) {
                    this.idEnderecoField = value;
                    this.RaisePropertyChanged("idEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idFuncionario {
            get {
                return this.idFuncionarioField;
            }
            set {
                if ((this.idFuncionarioField.Equals(value) != true)) {
                    this.idFuncionarioField = value;
                    this.RaisePropertyChanged("idFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSite {
            get {
                return this.idSiteField;
            }
            set {
                if ((this.idSiteField.Equals(value) != true)) {
                    this.idSiteField = value;
                    this.RaisePropertyChanged("idSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idTransportador {
            get {
                return this.idTransportadorField;
            }
            set {
                if ((this.idTransportadorField.Equals(value) != true)) {
                    this.idTransportadorField = value;
                    this.RaisePropertyChanged("idTransportador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nNumero {
            get {
                return this.nNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.nNumeroField, value) != true)) {
                    this.nNumeroField = value;
                    this.RaisePropertyChanged("nNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object objCidade {
            get {
                return this.objCidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.objCidadeField, value) != true)) {
                    this.objCidadeField = value;
                    this.RaisePropertyChanged("objCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stLogradouro {
            get {
                return this.stLogradouroField;
            }
            set {
                if ((this.stLogradouroField.Equals(value) != true)) {
                    this.stLogradouroField = value;
                    this.RaisePropertyChanged("stLogradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> stPrincipal {
            get {
                return this.stPrincipalField;
            }
            set {
                if ((this.stPrincipalField.Equals(value) != true)) {
                    this.stPrincipalField = value;
                    this.RaisePropertyChanged("stPrincipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stTipoEndereco {
            get {
                return this.stTipoEnderecoField;
            }
            set {
                if ((this.stTipoEnderecoField.Equals(value) != true)) {
                    this.stTipoEnderecoField = value;
                    this.RaisePropertyChanged("stTipoEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xBairro {
            get {
                return this.xBairroField;
            }
            set {
                if ((object.ReferenceEquals(this.xBairroField, value) != true)) {
                    this.xBairroField = value;
                    this.RaisePropertyChanged("xBairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xCEP {
            get {
                return this.xCEPField;
            }
            set {
                if ((object.ReferenceEquals(this.xCEPField, value) != true)) {
                    this.xCEPField = value;
                    this.RaisePropertyChanged("xCEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xCaixaPostal {
            get {
                return this.xCaixaPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.xCaixaPostalField, value) != true)) {
                    this.xCaixaPostalField = value;
                    this.RaisePropertyChanged("xCaixaPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xCidade {
            get {
                return this.xCidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.xCidadeField, value) != true)) {
                    this.xCidadeField = value;
                    this.RaisePropertyChanged("xCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xComplemento {
            get {
                return this.xComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.xComplementoField, value) != true)) {
                    this.xComplementoField = value;
                    this.RaisePropertyChanged("xComplemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xEndereco {
            get {
                return this.xEnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.xEnderecoField, value) != true)) {
                    this.xEnderecoField = value;
                    this.RaisePropertyChanged("xEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xNome {
            get {
                return this.xNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.xNomeField, value) != true)) {
                    this.xNomeField = value;
                    this.RaisePropertyChanged("xNome");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf_ParametroEmpresa.Iwcf_EmpresaParametros")]
    public interface Iwcf_EmpresaParametros {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_EmpresaParametros/getEmpresaParametros", ReplyAction="http://tempuri.org/Iwcf_EmpresaParametros/getEmpresaParametrosResponse")]
        HLP.Entries.Model.Models.Gerais.EmpresaModel getEmpresaParametros(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_EmpresaParametros/getEmpresaParametros", ReplyAction="http://tempuri.org/Iwcf_EmpresaParametros/getEmpresaParametrosResponse")]
        System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.EmpresaModel> getEmpresaParametrosAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_EmpresaParametros/saveEmpresaParamestros", ReplyAction="http://tempuri.org/Iwcf_EmpresaParametros/saveEmpresaParamestrosResponse")]
        void saveEmpresaParamestros(HLP.Entries.Model.Models.Gerais.EmpresaParametrosModel objEmpresaParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_EmpresaParametros/saveEmpresaParamestros", ReplyAction="http://tempuri.org/Iwcf_EmpresaParametros/saveEmpresaParamestrosResponse")]
        System.Threading.Tasks.Task saveEmpresaParamestrosAsync(HLP.Entries.Model.Models.Gerais.EmpresaParametrosModel objEmpresaParametros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iwcf_EmpresaParametrosChannel : HLP.Entries.Services.wcf_ParametroEmpresa.Iwcf_EmpresaParametros, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iwcf_EmpresaParametrosClient : System.ServiceModel.ClientBase<HLP.Entries.Services.wcf_ParametroEmpresa.Iwcf_EmpresaParametros>, HLP.Entries.Services.wcf_ParametroEmpresa.Iwcf_EmpresaParametros {
        
        public Iwcf_EmpresaParametrosClient() {
        }
        
        public Iwcf_EmpresaParametrosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iwcf_EmpresaParametrosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_EmpresaParametrosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_EmpresaParametrosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HLP.Entries.Model.Models.Gerais.EmpresaModel getEmpresaParametros(int idEmpresa) {
            return base.Channel.getEmpresaParametros(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.EmpresaModel> getEmpresaParametrosAsync(int idEmpresa) {
            return base.Channel.getEmpresaParametrosAsync(idEmpresa);
        }
        
        public void saveEmpresaParamestros(HLP.Entries.Model.Models.Gerais.EmpresaParametrosModel objEmpresaParametros) {
            base.Channel.saveEmpresaParamestros(objEmpresaParametros);
        }
        
        public System.Threading.Tasks.Task saveEmpresaParamestrosAsync(HLP.Entries.Model.Models.Gerais.EmpresaParametrosModel objEmpresaParametros) {
            return base.Channel.saveEmpresaParamestrosAsync(objEmpresaParametros);
        }
    }
}
