//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Comum.Facade.produtoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelBase", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Comum.Facade.produtoService.ConversaoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Comum.Facade.produtoService.Produto_Fornecedor_HomologadoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Comum.Facade.produtoService.Produto_RevisaoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Comum.Facade.produtoService.ProdutoModel))]
    public partial class modelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.produtoService.PesquisaPadraoModelContract[] lcamposSqlNotNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.produtoService.statusModel statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.produtoService.PesquisaPadraoModelContract[] lcamposSqlNotNull {
            get {
                return this.lcamposSqlNotNullField;
            }
            set {
                if ((object.ReferenceEquals(this.lcamposSqlNotNullField, value) != true)) {
                    this.lcamposSqlNotNullField = value;
                    this.RaisePropertyChanged("lcamposSqlNotNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.produtoService.statusModel status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversaoModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Entries.Model.Models.Gerais")]
    [System.SerializableAttribute()]
    public partial class ConversaoModel : HLP.Comum.Facade.produtoService.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.produtoService.TipoArredondamento enumTipoArredondamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idConversaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDeUnidadeMedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idParaUnidadeMedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nFatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nQuantidadeAdicionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stArredondarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.produtoService.TipoArredondamento enumTipoArredondamento {
            get {
                return this.enumTipoArredondamentoField;
            }
            set {
                if ((this.enumTipoArredondamentoField.Equals(value) != true)) {
                    this.enumTipoArredondamentoField = value;
                    this.RaisePropertyChanged("enumTipoArredondamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idConversao {
            get {
                return this.idConversaoField;
            }
            set {
                if ((this.idConversaoField.Equals(value) != true)) {
                    this.idConversaoField = value;
                    this.RaisePropertyChanged("idConversao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDeUnidadeMedida {
            get {
                return this.idDeUnidadeMedidaField;
            }
            set {
                if ((this.idDeUnidadeMedidaField.Equals(value) != true)) {
                    this.idDeUnidadeMedidaField = value;
                    this.RaisePropertyChanged("idDeUnidadeMedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idParaUnidadeMedida {
            get {
                return this.idParaUnidadeMedidaField;
            }
            set {
                if ((this.idParaUnidadeMedidaField.Equals(value) != true)) {
                    this.idParaUnidadeMedidaField = value;
                    this.RaisePropertyChanged("idParaUnidadeMedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProduto {
            get {
                return this.idProdutoField;
            }
            set {
                if ((this.idProdutoField.Equals(value) != true)) {
                    this.idProdutoField = value;
                    this.RaisePropertyChanged("idProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nFator {
            get {
                return this.nFatorField;
            }
            set {
                if ((this.nFatorField.Equals(value) != true)) {
                    this.nFatorField = value;
                    this.RaisePropertyChanged("nFator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nQuantidadeAdicional {
            get {
                return this.nQuantidadeAdicionalField;
            }
            set {
                if ((this.nQuantidadeAdicionalField.Equals(value) != true)) {
                    this.nQuantidadeAdicionalField = value;
                    this.RaisePropertyChanged("nQuantidadeAdicional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stArredondar {
            get {
                return this.stArredondarField;
            }
            set {
                if ((this.stArredondarField.Equals(value) != true)) {
                    this.stArredondarField = value;
                    this.RaisePropertyChanged("stArredondar");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto_Fornecedor_HomologadoModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Entries.Model.Models.Comercial")]
    [System.SerializableAttribute()]
    public partial class Produto_Fornecedor_HomologadoModel : HLP.Comum.Facade.produtoService.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idClienteFornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idProdutoFornecedorHomologadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nLeadTimeEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nLoteMinimoCompraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idClienteFornecedor {
            get {
                return this.idClienteFornecedorField;
            }
            set {
                if ((this.idClienteFornecedorField.Equals(value) != true)) {
                    this.idClienteFornecedorField = value;
                    this.RaisePropertyChanged("idClienteFornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProduto {
            get {
                return this.idProdutoField;
            }
            set {
                if ((this.idProdutoField.Equals(value) != true)) {
                    this.idProdutoField = value;
                    this.RaisePropertyChanged("idProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProdutoFornecedorHomologado {
            get {
                return this.idProdutoFornecedorHomologadoField;
            }
            set {
                if ((this.idProdutoFornecedorHomologadoField.Equals(value) != true)) {
                    this.idProdutoFornecedorHomologadoField = value;
                    this.RaisePropertyChanged("idProdutoFornecedorHomologado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nLeadTimeEntrega {
            get {
                return this.nLeadTimeEntregaField;
            }
            set {
                if ((this.nLeadTimeEntregaField.Equals(value) != true)) {
                    this.nLeadTimeEntregaField = value;
                    this.RaisePropertyChanged("nLeadTimeEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nLoteMinimoCompra {
            get {
                return this.nLoteMinimoCompraField;
            }
            set {
                if ((this.nLoteMinimoCompraField.Equals(value) != true)) {
                    this.nLoteMinimoCompraField = value;
                    this.RaisePropertyChanged("nLoteMinimoCompra");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto_RevisaoModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Entries.Model.Models.Comercial")]
    [System.SerializableAttribute()]
    public partial class Produto_RevisaoModel : HLP.Comum.Facade.produtoService.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idProdutoRevisaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xRevisaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dFinal {
            get {
                return this.dFinalField;
            }
            set {
                if ((this.dFinalField.Equals(value) != true)) {
                    this.dFinalField = value;
                    this.RaisePropertyChanged("dFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dInicial {
            get {
                return this.dInicialField;
            }
            set {
                if ((this.dInicialField.Equals(value) != true)) {
                    this.dInicialField = value;
                    this.RaisePropertyChanged("dInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFuncionario {
            get {
                return this.idFuncionarioField;
            }
            set {
                if ((this.idFuncionarioField.Equals(value) != true)) {
                    this.idFuncionarioField = value;
                    this.RaisePropertyChanged("idFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProduto {
            get {
                return this.idProdutoField;
            }
            set {
                if ((this.idProdutoField.Equals(value) != true)) {
                    this.idProdutoField = value;
                    this.RaisePropertyChanged("idProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProdutoRevisao {
            get {
                return this.idProdutoRevisaoField;
            }
            set {
                if ((this.idProdutoRevisaoField.Equals(value) != true)) {
                    this.idProdutoRevisaoField = value;
                    this.RaisePropertyChanged("idProdutoRevisao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xRevisao {
            get {
                return this.xRevisaoField;
            }
            set {
                if ((object.ReferenceEquals(this.xRevisaoField, value) != true)) {
                    this.xRevisaoField = value;
                    this.RaisePropertyChanged("xRevisao");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Entries.Model.Models.Comercial")]
    [System.SerializableAttribute()]
    public partial class ProdutoModel : HLP.Comum.Facade.produtoService.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_centro_custoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IniLoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cAlternativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cEanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dValorVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan dleadTimeCotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan dleadTimePedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan dleadTimeRecebimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCSTCofinsCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCSTCofinsVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCSTIcmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCSTIpiCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCSTIpiVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCSTPisCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCSTPisVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idClassificacaoFiscalCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idClassificacaoFiscalVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCodigoIcmsPaiCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idCodigoIcmsPaiVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDepositoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFabricanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFamiliaProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idProdutoLocalizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idTipoServicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUnidadeMedidaComprasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUnidadeMedidaEstoqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUnidadeMedidaProducaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUnidadeMedidaVendasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.produtoService.Produto_Fornecedor_HomologadoModel[] lProduto_Fornecedor_HomologadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.produtoService.Produto_RevisaoModel[] lProduto_RevisaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.produtoService.ConversaoModel[] lProdutos_ConversaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nAlturaBrutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nEstoqueMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nEstoqueMinimoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nLarguraBrutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nLoteMinimoComprasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nPesoBrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nPesoLiquidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nPrazoValidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nProfundidadeBrutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pEntregaExcedenteCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pEntregaExcedenteVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pEntregaInsuficienteCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pEntregaInsuficienteVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pImportacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pInssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pPerdaConstanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pPerdaVariavelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stCustoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stCustoMedioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stFornecedorHomologadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stFornecedorHomologadoProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stInssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stLogisticaReversaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stOrigemMercadoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte tpLoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vAquisicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vPerdaConstanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vProducaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xFotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xInglesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xObsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xPesquisaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_centro_custo {
            get {
                return this.Cod_centro_custoField;
            }
            set {
                if ((this.Cod_centro_custoField.Equals(value) != true)) {
                    this.Cod_centro_custoField = value;
                    this.RaisePropertyChanged("Cod_centro_custo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IniLote {
            get {
                return this.IniLoteField;
            }
            set {
                if ((object.ReferenceEquals(this.IniLoteField, value) != true)) {
                    this.IniLoteField = value;
                    this.RaisePropertyChanged("IniLote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cAlternativo {
            get {
                return this.cAlternativoField;
            }
            set {
                if ((object.ReferenceEquals(this.cAlternativoField, value) != true)) {
                    this.cAlternativoField = value;
                    this.RaisePropertyChanged("cAlternativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cEan {
            get {
                return this.cEanField;
            }
            set {
                if ((object.ReferenceEquals(this.cEanField, value) != true)) {
                    this.cEanField = value;
                    this.RaisePropertyChanged("cEan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dBloqueio {
            get {
                return this.dBloqueioField;
            }
            set {
                if ((this.dBloqueioField.Equals(value) != true)) {
                    this.dBloqueioField = value;
                    this.RaisePropertyChanged("dBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dCadastro {
            get {
                return this.dCadastroField;
            }
            set {
                if ((this.dCadastroField.Equals(value) != true)) {
                    this.dCadastroField = value;
                    this.RaisePropertyChanged("dCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dValorVenda {
            get {
                return this.dValorVendaField;
            }
            set {
                if ((this.dValorVendaField.Equals(value) != true)) {
                    this.dValorVendaField = value;
                    this.RaisePropertyChanged("dValorVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan dleadTimeCotacao {
            get {
                return this.dleadTimeCotacaoField;
            }
            set {
                if ((this.dleadTimeCotacaoField.Equals(value) != true)) {
                    this.dleadTimeCotacaoField = value;
                    this.RaisePropertyChanged("dleadTimeCotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan dleadTimePedido {
            get {
                return this.dleadTimePedidoField;
            }
            set {
                if ((this.dleadTimePedidoField.Equals(value) != true)) {
                    this.dleadTimePedidoField = value;
                    this.RaisePropertyChanged("dleadTimePedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan dleadTimeRecebimento {
            get {
                return this.dleadTimeRecebimentoField;
            }
            set {
                if ((this.dleadTimeRecebimentoField.Equals(value) != true)) {
                    this.dleadTimeRecebimentoField = value;
                    this.RaisePropertyChanged("dleadTimeRecebimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCSTCofinsCompra {
            get {
                return this.idCSTCofinsCompraField;
            }
            set {
                if ((this.idCSTCofinsCompraField.Equals(value) != true)) {
                    this.idCSTCofinsCompraField = value;
                    this.RaisePropertyChanged("idCSTCofinsCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCSTCofinsVenda {
            get {
                return this.idCSTCofinsVendaField;
            }
            set {
                if ((this.idCSTCofinsVendaField.Equals(value) != true)) {
                    this.idCSTCofinsVendaField = value;
                    this.RaisePropertyChanged("idCSTCofinsVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCSTIcms {
            get {
                return this.idCSTIcmsField;
            }
            set {
                if ((this.idCSTIcmsField.Equals(value) != true)) {
                    this.idCSTIcmsField = value;
                    this.RaisePropertyChanged("idCSTIcms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCSTIpiCompra {
            get {
                return this.idCSTIpiCompraField;
            }
            set {
                if ((this.idCSTIpiCompraField.Equals(value) != true)) {
                    this.idCSTIpiCompraField = value;
                    this.RaisePropertyChanged("idCSTIpiCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCSTIpiVenda {
            get {
                return this.idCSTIpiVendaField;
            }
            set {
                if ((this.idCSTIpiVendaField.Equals(value) != true)) {
                    this.idCSTIpiVendaField = value;
                    this.RaisePropertyChanged("idCSTIpiVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCSTPisCompra {
            get {
                return this.idCSTPisCompraField;
            }
            set {
                if ((this.idCSTPisCompraField.Equals(value) != true)) {
                    this.idCSTPisCompraField = value;
                    this.RaisePropertyChanged("idCSTPisCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCSTPisVenda {
            get {
                return this.idCSTPisVendaField;
            }
            set {
                if ((this.idCSTPisVendaField.Equals(value) != true)) {
                    this.idCSTPisVendaField = value;
                    this.RaisePropertyChanged("idCSTPisVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idClassificacaoFiscalCompra {
            get {
                return this.idClassificacaoFiscalCompraField;
            }
            set {
                if ((this.idClassificacaoFiscalCompraField.Equals(value) != true)) {
                    this.idClassificacaoFiscalCompraField = value;
                    this.RaisePropertyChanged("idClassificacaoFiscalCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idClassificacaoFiscalVenda {
            get {
                return this.idClassificacaoFiscalVendaField;
            }
            set {
                if ((this.idClassificacaoFiscalVendaField.Equals(value) != true)) {
                    this.idClassificacaoFiscalVendaField = value;
                    this.RaisePropertyChanged("idClassificacaoFiscalVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCodigoIcmsPaiCompra {
            get {
                return this.idCodigoIcmsPaiCompraField;
            }
            set {
                if ((this.idCodigoIcmsPaiCompraField.Equals(value) != true)) {
                    this.idCodigoIcmsPaiCompraField = value;
                    this.RaisePropertyChanged("idCodigoIcmsPaiCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCodigoIcmsPaiVenda {
            get {
                return this.idCodigoIcmsPaiVendaField;
            }
            set {
                if ((this.idCodigoIcmsPaiVendaField.Equals(value) != true)) {
                    this.idCodigoIcmsPaiVendaField = value;
                    this.RaisePropertyChanged("idCodigoIcmsPaiVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDeposito {
            get {
                return this.idDepositoField;
            }
            set {
                if ((this.idDepositoField.Equals(value) != true)) {
                    this.idDepositoField = value;
                    this.RaisePropertyChanged("idDeposito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFabricante {
            get {
                return this.idFabricanteField;
            }
            set {
                if ((this.idFabricanteField.Equals(value) != true)) {
                    this.idFabricanteField = value;
                    this.RaisePropertyChanged("idFabricante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFamiliaProduto {
            get {
                return this.idFamiliaProdutoField;
            }
            set {
                if ((this.idFamiliaProdutoField.Equals(value) != true)) {
                    this.idFamiliaProdutoField = value;
                    this.RaisePropertyChanged("idFamiliaProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFuncionario {
            get {
                return this.idFuncionarioField;
            }
            set {
                if ((this.idFuncionarioField.Equals(value) != true)) {
                    this.idFuncionarioField = value;
                    this.RaisePropertyChanged("idFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProduto {
            get {
                return this.idProdutoField;
            }
            set {
                if ((this.idProdutoField.Equals(value) != true)) {
                    this.idProdutoField = value;
                    this.RaisePropertyChanged("idProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProdutoLocalizacao {
            get {
                return this.idProdutoLocalizacaoField;
            }
            set {
                if ((this.idProdutoLocalizacaoField.Equals(value) != true)) {
                    this.idProdutoLocalizacaoField = value;
                    this.RaisePropertyChanged("idProdutoLocalizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoProduto {
            get {
                return this.idTipoProdutoField;
            }
            set {
                if ((this.idTipoProdutoField.Equals(value) != true)) {
                    this.idTipoProdutoField = value;
                    this.RaisePropertyChanged("idTipoProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idTipoServico {
            get {
                return this.idTipoServicoField;
            }
            set {
                if ((this.idTipoServicoField.Equals(value) != true)) {
                    this.idTipoServicoField = value;
                    this.RaisePropertyChanged("idTipoServico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUnidadeMedidaCompras {
            get {
                return this.idUnidadeMedidaComprasField;
            }
            set {
                if ((this.idUnidadeMedidaComprasField.Equals(value) != true)) {
                    this.idUnidadeMedidaComprasField = value;
                    this.RaisePropertyChanged("idUnidadeMedidaCompras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUnidadeMedidaEstoque {
            get {
                return this.idUnidadeMedidaEstoqueField;
            }
            set {
                if ((this.idUnidadeMedidaEstoqueField.Equals(value) != true)) {
                    this.idUnidadeMedidaEstoqueField = value;
                    this.RaisePropertyChanged("idUnidadeMedidaEstoque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUnidadeMedidaProducao {
            get {
                return this.idUnidadeMedidaProducaoField;
            }
            set {
                if ((this.idUnidadeMedidaProducaoField.Equals(value) != true)) {
                    this.idUnidadeMedidaProducaoField = value;
                    this.RaisePropertyChanged("idUnidadeMedidaProducao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUnidadeMedidaVendas {
            get {
                return this.idUnidadeMedidaVendasField;
            }
            set {
                if ((this.idUnidadeMedidaVendasField.Equals(value) != true)) {
                    this.idUnidadeMedidaVendasField = value;
                    this.RaisePropertyChanged("idUnidadeMedidaVendas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.produtoService.Produto_Fornecedor_HomologadoModel[] lProduto_Fornecedor_Homologado {
            get {
                return this.lProduto_Fornecedor_HomologadoField;
            }
            set {
                if ((object.ReferenceEquals(this.lProduto_Fornecedor_HomologadoField, value) != true)) {
                    this.lProduto_Fornecedor_HomologadoField = value;
                    this.RaisePropertyChanged("lProduto_Fornecedor_Homologado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.produtoService.Produto_RevisaoModel[] lProduto_Revisao {
            get {
                return this.lProduto_RevisaoField;
            }
            set {
                if ((object.ReferenceEquals(this.lProduto_RevisaoField, value) != true)) {
                    this.lProduto_RevisaoField = value;
                    this.RaisePropertyChanged("lProduto_Revisao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.produtoService.ConversaoModel[] lProdutos_Conversao {
            get {
                return this.lProdutos_ConversaoField;
            }
            set {
                if ((object.ReferenceEquals(this.lProdutos_ConversaoField, value) != true)) {
                    this.lProdutos_ConversaoField = value;
                    this.RaisePropertyChanged("lProdutos_Conversao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nAlturaBruta {
            get {
                return this.nAlturaBrutaField;
            }
            set {
                if ((this.nAlturaBrutaField.Equals(value) != true)) {
                    this.nAlturaBrutaField = value;
                    this.RaisePropertyChanged("nAlturaBruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nEstoqueMaximo {
            get {
                return this.nEstoqueMaximoField;
            }
            set {
                if ((this.nEstoqueMaximoField.Equals(value) != true)) {
                    this.nEstoqueMaximoField = value;
                    this.RaisePropertyChanged("nEstoqueMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nEstoqueMinimo {
            get {
                return this.nEstoqueMinimoField;
            }
            set {
                if ((this.nEstoqueMinimoField.Equals(value) != true)) {
                    this.nEstoqueMinimoField = value;
                    this.RaisePropertyChanged("nEstoqueMinimo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nLarguraBruta {
            get {
                return this.nLarguraBrutaField;
            }
            set {
                if ((this.nLarguraBrutaField.Equals(value) != true)) {
                    this.nLarguraBrutaField = value;
                    this.RaisePropertyChanged("nLarguraBruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nLoteMinimoCompras {
            get {
                return this.nLoteMinimoComprasField;
            }
            set {
                if ((this.nLoteMinimoComprasField.Equals(value) != true)) {
                    this.nLoteMinimoComprasField = value;
                    this.RaisePropertyChanged("nLoteMinimoCompras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nPesoBruto {
            get {
                return this.nPesoBrutoField;
            }
            set {
                if ((this.nPesoBrutoField.Equals(value) != true)) {
                    this.nPesoBrutoField = value;
                    this.RaisePropertyChanged("nPesoBruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nPesoLiquido {
            get {
                return this.nPesoLiquidoField;
            }
            set {
                if ((this.nPesoLiquidoField.Equals(value) != true)) {
                    this.nPesoLiquidoField = value;
                    this.RaisePropertyChanged("nPesoLiquido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nPrazoValidade {
            get {
                return this.nPrazoValidadeField;
            }
            set {
                if ((this.nPrazoValidadeField.Equals(value) != true)) {
                    this.nPrazoValidadeField = value;
                    this.RaisePropertyChanged("nPrazoValidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nProfundidadeBruta {
            get {
                return this.nProfundidadeBrutaField;
            }
            set {
                if ((this.nProfundidadeBrutaField.Equals(value) != true)) {
                    this.nProfundidadeBrutaField = value;
                    this.RaisePropertyChanged("nProfundidadeBruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pEntregaExcedenteCompra {
            get {
                return this.pEntregaExcedenteCompraField;
            }
            set {
                if ((this.pEntregaExcedenteCompraField.Equals(value) != true)) {
                    this.pEntregaExcedenteCompraField = value;
                    this.RaisePropertyChanged("pEntregaExcedenteCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pEntregaExcedenteVenda {
            get {
                return this.pEntregaExcedenteVendaField;
            }
            set {
                if ((this.pEntregaExcedenteVendaField.Equals(value) != true)) {
                    this.pEntregaExcedenteVendaField = value;
                    this.RaisePropertyChanged("pEntregaExcedenteVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pEntregaInsuficienteCompra {
            get {
                return this.pEntregaInsuficienteCompraField;
            }
            set {
                if ((this.pEntregaInsuficienteCompraField.Equals(value) != true)) {
                    this.pEntregaInsuficienteCompraField = value;
                    this.RaisePropertyChanged("pEntregaInsuficienteCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pEntregaInsuficienteVenda {
            get {
                return this.pEntregaInsuficienteVendaField;
            }
            set {
                if ((this.pEntregaInsuficienteVendaField.Equals(value) != true)) {
                    this.pEntregaInsuficienteVendaField = value;
                    this.RaisePropertyChanged("pEntregaInsuficienteVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pImportacao {
            get {
                return this.pImportacaoField;
            }
            set {
                if ((this.pImportacaoField.Equals(value) != true)) {
                    this.pImportacaoField = value;
                    this.RaisePropertyChanged("pImportacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pInss {
            get {
                return this.pInssField;
            }
            set {
                if ((this.pInssField.Equals(value) != true)) {
                    this.pInssField = value;
                    this.RaisePropertyChanged("pInss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pPerdaConstante {
            get {
                return this.pPerdaConstanteField;
            }
            set {
                if ((this.pPerdaConstanteField.Equals(value) != true)) {
                    this.pPerdaConstanteField = value;
                    this.RaisePropertyChanged("pPerdaConstante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pPerdaVariavel {
            get {
                return this.pPerdaVariavelField;
            }
            set {
                if ((this.pPerdaVariavelField.Equals(value) != true)) {
                    this.pPerdaVariavelField = value;
                    this.RaisePropertyChanged("pPerdaVariavel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stCusto {
            get {
                return this.stCustoField;
            }
            set {
                if ((this.stCustoField.Equals(value) != true)) {
                    this.stCustoField = value;
                    this.RaisePropertyChanged("stCusto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stCustoMedio {
            get {
                return this.stCustoMedioField;
            }
            set {
                if ((this.stCustoMedioField.Equals(value) != true)) {
                    this.stCustoMedioField = value;
                    this.RaisePropertyChanged("stCustoMedio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stFornecedorHomologado {
            get {
                return this.stFornecedorHomologadoField;
            }
            set {
                if ((this.stFornecedorHomologadoField.Equals(value) != true)) {
                    this.stFornecedorHomologadoField = value;
                    this.RaisePropertyChanged("stFornecedorHomologado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stFornecedorHomologadoProduto {
            get {
                return this.stFornecedorHomologadoProdutoField;
            }
            set {
                if ((this.stFornecedorHomologadoProdutoField.Equals(value) != true)) {
                    this.stFornecedorHomologadoProdutoField = value;
                    this.RaisePropertyChanged("stFornecedorHomologadoProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stInss {
            get {
                return this.stInssField;
            }
            set {
                if ((this.stInssField.Equals(value) != true)) {
                    this.stInssField = value;
                    this.RaisePropertyChanged("stInss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stLogisticaReversa {
            get {
                return this.stLogisticaReversaField;
            }
            set {
                if ((this.stLogisticaReversaField.Equals(value) != true)) {
                    this.stLogisticaReversaField = value;
                    this.RaisePropertyChanged("stLogisticaReversa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stOrigemMercadoria {
            get {
                return this.stOrigemMercadoriaField;
            }
            set {
                if ((this.stOrigemMercadoriaField.Equals(value) != true)) {
                    this.stOrigemMercadoriaField = value;
                    this.RaisePropertyChanged("stOrigemMercadoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte tpLote {
            get {
                return this.tpLoteField;
            }
            set {
                if ((this.tpLoteField.Equals(value) != true)) {
                    this.tpLoteField = value;
                    this.RaisePropertyChanged("tpLote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vAquisicao {
            get {
                return this.vAquisicaoField;
            }
            set {
                if ((this.vAquisicaoField.Equals(value) != true)) {
                    this.vAquisicaoField = value;
                    this.RaisePropertyChanged("vAquisicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vCompra {
            get {
                return this.vCompraField;
            }
            set {
                if ((this.vCompraField.Equals(value) != true)) {
                    this.vCompraField = value;
                    this.RaisePropertyChanged("vCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vPerdaConstante {
            get {
                return this.vPerdaConstanteField;
            }
            set {
                if ((this.vPerdaConstanteField.Equals(value) != true)) {
                    this.vPerdaConstanteField = value;
                    this.RaisePropertyChanged("vPerdaConstante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vProducao {
            get {
                return this.vProducaoField;
            }
            set {
                if ((this.vProducaoField.Equals(value) != true)) {
                    this.vProducaoField = value;
                    this.RaisePropertyChanged("vProducao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vVenda {
            get {
                return this.vVendaField;
            }
            set {
                if ((this.vVendaField.Equals(value) != true)) {
                    this.vVendaField = value;
                    this.RaisePropertyChanged("vVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xComercial {
            get {
                return this.xComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.xComercialField, value) != true)) {
                    this.xComercialField = value;
                    this.RaisePropertyChanged("xComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xFiscal {
            get {
                return this.xFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.xFiscalField, value) != true)) {
                    this.xFiscalField = value;
                    this.RaisePropertyChanged("xFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xFoto {
            get {
                return this.xFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.xFotoField, value) != true)) {
                    this.xFotoField = value;
                    this.RaisePropertyChanged("xFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xIngles {
            get {
                return this.xInglesField;
            }
            set {
                if ((object.ReferenceEquals(this.xInglesField, value) != true)) {
                    this.xInglesField = value;
                    this.RaisePropertyChanged("xIngles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xObs {
            get {
                return this.xObsField;
            }
            set {
                if ((object.ReferenceEquals(this.xObsField, value) != true)) {
                    this.xObsField = value;
                    this.RaisePropertyChanged("xObs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xPesquisa {
            get {
                return this.xPesquisaField;
            }
            set {
                if ((object.ReferenceEquals(this.xPesquisaField, value) != true)) {
                    this.xPesquisaField = value;
                    this.RaisePropertyChanged("xPesquisa");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PesquisaPadraoModelContract", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Components")]
    [System.SerializableAttribute()]
    public partial class PesquisaPadraoModelContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CHARACTER_MAXIMUM_LENGTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLUMN_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IS_NULLABLEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHARACTER_MAXIMUM_LENGTH {
            get {
                return this.CHARACTER_MAXIMUM_LENGTHField;
            }
            set {
                if ((this.CHARACTER_MAXIMUM_LENGTHField.Equals(value) != true)) {
                    this.CHARACTER_MAXIMUM_LENGTHField = value;
                    this.RaisePropertyChanged("CHARACTER_MAXIMUM_LENGTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLUMN_NAME {
            get {
                return this.COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COLUMN_NAMEField, value) != true)) {
                    this.COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("COLUMN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_TYPEField, value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IS_NULLABLE {
            get {
                return this.IS_NULLABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.IS_NULLABLEField, value) != true)) {
                    this.IS_NULLABLEField = value;
                    this.RaisePropertyChanged("IS_NULLABLE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="statusModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Resources.RecursosBases")]
    public enum statusModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nenhum = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        criado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        alterado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        excluido = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoArredondamento", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Resources.RecursosBases")]
    public enum TipoArredondamento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PARABAIXO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PARACIMA = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="produtoService.IserviceProduto")]
    public interface IserviceProduto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/getProduto", ReplyAction="http://tempuri.org/IserviceProduto/getProdutoResponse")]
        HLP.Comum.Facade.produtoService.ProdutoModel getProduto(int idProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/getProduto", ReplyAction="http://tempuri.org/IserviceProduto/getProdutoResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Facade.produtoService.ProdutoModel> getProdutoAsync(int idProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/saveProduto", ReplyAction="http://tempuri.org/IserviceProduto/saveProdutoResponse")]
        HLP.Comum.Facade.produtoService.ProdutoModel saveProduto(HLP.Comum.Facade.produtoService.ProdutoModel objProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/saveProduto", ReplyAction="http://tempuri.org/IserviceProduto/saveProdutoResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Facade.produtoService.ProdutoModel> saveProdutoAsync(HLP.Comum.Facade.produtoService.ProdutoModel objProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/deleteProduto", ReplyAction="http://tempuri.org/IserviceProduto/deleteProdutoResponse")]
        bool deleteProduto(int idProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/deleteProduto", ReplyAction="http://tempuri.org/IserviceProduto/deleteProdutoResponse")]
        System.Threading.Tasks.Task<bool> deleteProdutoAsync(int idProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/copyProduto", ReplyAction="http://tempuri.org/IserviceProduto/copyProdutoResponse")]
        int copyProduto(HLP.Comum.Facade.produtoService.ProdutoModel objProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/copyProduto", ReplyAction="http://tempuri.org/IserviceProduto/copyProdutoResponse")]
        System.Threading.Tasks.Task<int> copyProdutoAsync(HLP.Comum.Facade.produtoService.ProdutoModel objProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/getAll", ReplyAction="http://tempuri.org/IserviceProduto/getAllResponse")]
        HLP.Comum.Facade.produtoService.ProdutoModel[] getAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceProduto/getAll", ReplyAction="http://tempuri.org/IserviceProduto/getAllResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Facade.produtoService.ProdutoModel[]> getAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IserviceProdutoChannel : HLP.Comum.Facade.produtoService.IserviceProduto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IserviceProdutoClient : System.ServiceModel.ClientBase<HLP.Comum.Facade.produtoService.IserviceProduto>, HLP.Comum.Facade.produtoService.IserviceProduto {
        
        public IserviceProdutoClient() {
        }
        
        public IserviceProdutoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IserviceProdutoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceProdutoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceProdutoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HLP.Comum.Facade.produtoService.ProdutoModel getProduto(int idProduto) {
            return base.Channel.getProduto(idProduto);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Facade.produtoService.ProdutoModel> getProdutoAsync(int idProduto) {
            return base.Channel.getProdutoAsync(idProduto);
        }
        
        public HLP.Comum.Facade.produtoService.ProdutoModel saveProduto(HLP.Comum.Facade.produtoService.ProdutoModel objProduto) {
            return base.Channel.saveProduto(objProduto);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Facade.produtoService.ProdutoModel> saveProdutoAsync(HLP.Comum.Facade.produtoService.ProdutoModel objProduto) {
            return base.Channel.saveProdutoAsync(objProduto);
        }
        
        public bool deleteProduto(int idProduto) {
            return base.Channel.deleteProduto(idProduto);
        }
        
        public System.Threading.Tasks.Task<bool> deleteProdutoAsync(int idProduto) {
            return base.Channel.deleteProdutoAsync(idProduto);
        }
        
        public int copyProduto(HLP.Comum.Facade.produtoService.ProdutoModel objProduto) {
            return base.Channel.copyProduto(objProduto);
        }
        
        public System.Threading.Tasks.Task<int> copyProdutoAsync(HLP.Comum.Facade.produtoService.ProdutoModel objProduto) {
            return base.Channel.copyProdutoAsync(objProduto);
        }
        
        public HLP.Comum.Facade.produtoService.ProdutoModel[] getAll() {
            return base.Channel.getAll();
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Facade.produtoService.ProdutoModel[]> getAllAsync() {
            return base.Channel.getAllAsync();
        }
    }
}
