//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Entries.ViewModel.Familia_ProdutoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelBase", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.Familia_Produto_ClassesModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.Familia_produtoModel))]
    public partial class modelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<HLP.Entries.ViewModel.Familia_ProdutoService.PesquisaPadraoModelContract> lcamposSqlNotNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Entries.ViewModel.Familia_ProdutoService.statusModel statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<HLP.Entries.ViewModel.Familia_ProdutoService.PesquisaPadraoModelContract> lcamposSqlNotNull {
            get {
                return this.lcamposSqlNotNullField;
            }
            set {
                if ((object.ReferenceEquals(this.lcamposSqlNotNullField, value) != true)) {
                    this.lcamposSqlNotNullField = value;
                    this.RaisePropertyChanged("lcamposSqlNotNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Entries.ViewModel.Familia_ProdutoService.statusModel status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PesquisaPadraoModelContract", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Components")]
    [System.SerializableAttribute()]
    public partial class PesquisaPadraoModelContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CHARACTER_MAXIMUM_LENGTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLUMN_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IS_NULLABLEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHARACTER_MAXIMUM_LENGTH {
            get {
                return this.CHARACTER_MAXIMUM_LENGTHField;
            }
            set {
                if ((this.CHARACTER_MAXIMUM_LENGTHField.Equals(value) != true)) {
                    this.CHARACTER_MAXIMUM_LENGTHField = value;
                    this.RaisePropertyChanged("CHARACTER_MAXIMUM_LENGTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLUMN_NAME {
            get {
                return this.COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COLUMN_NAMEField, value) != true)) {
                    this.COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("COLUMN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_TYPEField, value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IS_NULLABLE {
            get {
                return this.IS_NULLABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.IS_NULLABLEField, value) != true)) {
                    this.IS_NULLABLEField = value;
                    this.RaisePropertyChanged("IS_NULLABLE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="statusModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Resources.RecursosBases")]
    public enum statusModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nenhum = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        criado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        alterado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        excluido = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Familia_ProdutoService.IserviceFamiliaProduto")]
    public interface IserviceFamiliaProduto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceFamiliaProduto/GetObject", ReplyAction="http://tempuri.org/IserviceFamiliaProduto/GetObjectResponse")]
        HLP.Entries.Model.Models.Gerais.Familia_produtoModel GetObject(int idFamiliaProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceFamiliaProduto/GetObject", ReplyAction="http://tempuri.org/IserviceFamiliaProduto/GetObjectResponse")]
        System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Familia_produtoModel> GetObjectAsync(int idFamiliaProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceFamiliaProduto/Save", ReplyAction="http://tempuri.org/IserviceFamiliaProduto/SaveResponse")]
        HLP.Entries.Model.Models.Gerais.Familia_produtoModel Save(HLP.Entries.Model.Models.Gerais.Familia_produtoModel familia_produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceFamiliaProduto/Save", ReplyAction="http://tempuri.org/IserviceFamiliaProduto/SaveResponse")]
        System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Familia_produtoModel> SaveAsync(HLP.Entries.Model.Models.Gerais.Familia_produtoModel familia_produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceFamiliaProduto/Delete", ReplyAction="http://tempuri.org/IserviceFamiliaProduto/DeleteResponse")]
        bool Delete(int idFamiliaProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceFamiliaProduto/Delete", ReplyAction="http://tempuri.org/IserviceFamiliaProduto/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int idFamiliaProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceFamiliaProduto/Copy", ReplyAction="http://tempuri.org/IserviceFamiliaProduto/CopyResponse")]
        HLP.Entries.Model.Models.Gerais.Familia_produtoModel Copy(HLP.Entries.Model.Models.Gerais.Familia_produtoModel familia_produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceFamiliaProduto/Copy", ReplyAction="http://tempuri.org/IserviceFamiliaProduto/CopyResponse")]
        System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Familia_produtoModel> CopyAsync(HLP.Entries.Model.Models.Gerais.Familia_produtoModel familia_produto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IserviceFamiliaProdutoChannel : HLP.Entries.ViewModel.Familia_ProdutoService.IserviceFamiliaProduto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IserviceFamiliaProdutoClient : System.ServiceModel.ClientBase<HLP.Entries.ViewModel.Familia_ProdutoService.IserviceFamiliaProduto>, HLP.Entries.ViewModel.Familia_ProdutoService.IserviceFamiliaProduto {
        
        public IserviceFamiliaProdutoClient() {
        }
        
        public IserviceFamiliaProdutoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IserviceFamiliaProdutoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceFamiliaProdutoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceFamiliaProdutoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HLP.Entries.Model.Models.Gerais.Familia_produtoModel GetObject(int idFamiliaProduto) {
            return base.Channel.GetObject(idFamiliaProduto);
        }
        
        public System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Familia_produtoModel> GetObjectAsync(int idFamiliaProduto) {
            return base.Channel.GetObjectAsync(idFamiliaProduto);
        }
        
        public HLP.Entries.Model.Models.Gerais.Familia_produtoModel Save(HLP.Entries.Model.Models.Gerais.Familia_produtoModel familia_produto) {
            return base.Channel.Save(familia_produto);
        }
        
        public System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Familia_produtoModel> SaveAsync(HLP.Entries.Model.Models.Gerais.Familia_produtoModel familia_produto) {
            return base.Channel.SaveAsync(familia_produto);
        }
        
        public bool Delete(int idFamiliaProduto) {
            return base.Channel.Delete(idFamiliaProduto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int idFamiliaProduto) {
            return base.Channel.DeleteAsync(idFamiliaProduto);
        }
        
        public HLP.Entries.Model.Models.Gerais.Familia_produtoModel Copy(HLP.Entries.Model.Models.Gerais.Familia_produtoModel familia_produto) {
            return base.Channel.Copy(familia_produto);
        }
        
        public System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Familia_produtoModel> CopyAsync(HLP.Entries.Model.Models.Gerais.Familia_produtoModel familia_produto) {
            return base.Channel.CopyAsync(familia_produto);
        }
    }
}
