//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Comum.ViewModel.HlpPesquisaPadraoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HlpPesquisaPadraoService.IservicePesquisaPadrao")]
    public interface IservicePesquisaPadrao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicePesquisaPadrao/GetTableInformation", ReplyAction="http://tempuri.org/IservicePesquisaPadrao/GetTableInformationResponse")]
        HLP.Comum.Model.Components.PesquisaPadraoModelContract[] GetTableInformation(string sViewName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicePesquisaPadrao/GetTableInformation", ReplyAction="http://tempuri.org/IservicePesquisaPadrao/GetTableInformationResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Model.Components.PesquisaPadraoModelContract[]> GetTableInformationAsync(string sViewName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicePesquisaPadrao/GetData", ReplyAction="http://tempuri.org/IservicePesquisaPadrao/GetDataResponse")]
        System.Data.DataSet GetData(string sSelect, bool addDefault, string sWhere, bool bOrdena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicePesquisaPadrao/GetData", ReplyAction="http://tempuri.org/IservicePesquisaPadrao/GetDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string sSelect, bool addDefault, string sWhere, bool bOrdena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IservicePesquisaPadraoChannel : HLP.Comum.ViewModel.HlpPesquisaPadraoService.IservicePesquisaPadrao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IservicePesquisaPadraoClient : System.ServiceModel.ClientBase<HLP.Comum.ViewModel.HlpPesquisaPadraoService.IservicePesquisaPadrao>, HLP.Comum.ViewModel.HlpPesquisaPadraoService.IservicePesquisaPadrao {
        
        public IservicePesquisaPadraoClient() {
        }
        
        public IservicePesquisaPadraoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IservicePesquisaPadraoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IservicePesquisaPadraoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IservicePesquisaPadraoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HLP.Comum.Model.Components.PesquisaPadraoModelContract[] GetTableInformation(string sViewName) {
            return base.Channel.GetTableInformation(sViewName);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Model.Components.PesquisaPadraoModelContract[]> GetTableInformationAsync(string sViewName) {
            return base.Channel.GetTableInformationAsync(sViewName);
        }
        
        public System.Data.DataSet GetData(string sSelect, bool addDefault, string sWhere, bool bOrdena) {
            return base.Channel.GetData(sSelect, addDefault, sWhere, bOrdena);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string sSelect, bool addDefault, string sWhere, bool bOrdena) {
            return base.Channel.GetDataAsync(sSelect, addDefault, sWhere, bOrdena);
        }
    }
}
