//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Comum.Facade.Lista_PrecoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelBase", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Comum.Facade.Lista_PrecoService.Lista_precoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel))]
    public partial class modelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.Lista_PrecoService.PesquisaPadraoModelContract[] lcamposSqlNotNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.Lista_PrecoService.statusModel statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.Lista_PrecoService.PesquisaPadraoModelContract[] lcamposSqlNotNull {
            get {
                return this.lcamposSqlNotNullField;
            }
            set {
                if ((object.ReferenceEquals(this.lcamposSqlNotNullField, value) != true)) {
                    this.lcamposSqlNotNullField = value;
                    this.RaisePropertyChanged("lcamposSqlNotNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.Lista_PrecoService.statusModel status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_precoModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Entries.Model.Models.Comercial")]
    [System.SerializableAttribute()]
    public partial class Lista_precoModel : HLP.Comum.Facade.Lista_PrecoService.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dAlteracaoCustoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idListaPrecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idListaPrecoPaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUnidadeMedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pAcrescimoMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pComissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pComissaoAprazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pComissaoAvistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pDescontoMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pLucroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pMarkupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pOutrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vCustoProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vVendaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dAlteracaoCusto {
            get {
                return this.dAlteracaoCustoField;
            }
            set {
                if ((this.dAlteracaoCustoField.Equals(value) != true)) {
                    this.dAlteracaoCustoField = value;
                    this.RaisePropertyChanged("dAlteracaoCusto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idListaPreco {
            get {
                return this.idListaPrecoField;
            }
            set {
                if ((this.idListaPrecoField.Equals(value) != true)) {
                    this.idListaPrecoField = value;
                    this.RaisePropertyChanged("idListaPreco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idListaPrecoPai {
            get {
                return this.idListaPrecoPaiField;
            }
            set {
                if ((this.idListaPrecoPaiField.Equals(value) != true)) {
                    this.idListaPrecoPaiField = value;
                    this.RaisePropertyChanged("idListaPrecoPai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProduto {
            get {
                return this.idProdutoField;
            }
            set {
                if ((this.idProdutoField.Equals(value) != true)) {
                    this.idProdutoField = value;
                    this.RaisePropertyChanged("idProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUnidadeMedida {
            get {
                return this.idUnidadeMedidaField;
            }
            set {
                if ((this.idUnidadeMedidaField.Equals(value) != true)) {
                    this.idUnidadeMedidaField = value;
                    this.RaisePropertyChanged("idUnidadeMedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pAcrescimoMaximo {
            get {
                return this.pAcrescimoMaximoField;
            }
            set {
                if ((this.pAcrescimoMaximoField.Equals(value) != true)) {
                    this.pAcrescimoMaximoField = value;
                    this.RaisePropertyChanged("pAcrescimoMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pComissao {
            get {
                return this.pComissaoField;
            }
            set {
                if ((this.pComissaoField.Equals(value) != true)) {
                    this.pComissaoField = value;
                    this.RaisePropertyChanged("pComissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pComissaoAprazo {
            get {
                return this.pComissaoAprazoField;
            }
            set {
                if ((this.pComissaoAprazoField.Equals(value) != true)) {
                    this.pComissaoAprazoField = value;
                    this.RaisePropertyChanged("pComissaoAprazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pComissaoAvista {
            get {
                return this.pComissaoAvistaField;
            }
            set {
                if ((this.pComissaoAvistaField.Equals(value) != true)) {
                    this.pComissaoAvistaField = value;
                    this.RaisePropertyChanged("pComissaoAvista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pDesconto {
            get {
                return this.pDescontoField;
            }
            set {
                if ((this.pDescontoField.Equals(value) != true)) {
                    this.pDescontoField = value;
                    this.RaisePropertyChanged("pDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pDescontoMaximo {
            get {
                return this.pDescontoMaximoField;
            }
            set {
                if ((this.pDescontoMaximoField.Equals(value) != true)) {
                    this.pDescontoMaximoField = value;
                    this.RaisePropertyChanged("pDescontoMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pLucro {
            get {
                return this.pLucroField;
            }
            set {
                if ((this.pLucroField.Equals(value) != true)) {
                    this.pLucroField = value;
                    this.RaisePropertyChanged("pLucro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pMarkup {
            get {
                return this.pMarkupField;
            }
            set {
                if ((this.pMarkupField.Equals(value) != true)) {
                    this.pMarkupField = value;
                    this.RaisePropertyChanged("pMarkup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pOutros {
            get {
                return this.pOutrosField;
            }
            set {
                if ((this.pOutrosField.Equals(value) != true)) {
                    this.pOutrosField = value;
                    this.RaisePropertyChanged("pOutros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vCustoProduto {
            get {
                return this.vCustoProdutoField;
            }
            set {
                if ((this.vCustoProdutoField.Equals(value) != true)) {
                    this.vCustoProdutoField = value;
                    this.RaisePropertyChanged("vCustoProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vVenda {
            get {
                return this.vVendaField;
            }
            set {
                if ((this.vVendaField.Equals(value) != true)) {
                    this.vVendaField = value;
                    this.RaisePropertyChanged("vVenda");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_Preco_PaiModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Entries.Model.Models.Comercial")]
    [System.SerializableAttribute()]
    public partial class Lista_Preco_PaiModel : HLP.Comum.Facade.Lista_PrecoService.modelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dListaPrecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dValidadeContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idListaPrecoOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idListaPrecoPaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Comum.Facade.Lista_PrecoService.Lista_precoModel[] lLista_precoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> nDiasSemAtualicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pAcressimoMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pDescontoMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> pPercentualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stAtualizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte stContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xCodigoListaPrecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xListaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xNrContratoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dListaPreco {
            get {
                return this.dListaPrecoField;
            }
            set {
                if ((this.dListaPrecoField.Equals(value) != true)) {
                    this.dListaPrecoField = value;
                    this.RaisePropertyChanged("dListaPreco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dValidadeContrato {
            get {
                return this.dValidadeContratoField;
            }
            set {
                if ((this.dValidadeContratoField.Equals(value) != true)) {
                    this.dValidadeContratoField = value;
                    this.RaisePropertyChanged("dValidadeContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idListaPrecoOrigem {
            get {
                return this.idListaPrecoOrigemField;
            }
            set {
                if ((this.idListaPrecoOrigemField.Equals(value) != true)) {
                    this.idListaPrecoOrigemField = value;
                    this.RaisePropertyChanged("idListaPrecoOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idListaPrecoPai {
            get {
                return this.idListaPrecoPaiField;
            }
            set {
                if ((this.idListaPrecoPaiField.Equals(value) != true)) {
                    this.idListaPrecoPaiField = value;
                    this.RaisePropertyChanged("idListaPrecoPai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Comum.Facade.Lista_PrecoService.Lista_precoModel[] lLista_preco {
            get {
                return this.lLista_precoField;
            }
            set {
                if ((object.ReferenceEquals(this.lLista_precoField, value) != true)) {
                    this.lLista_precoField = value;
                    this.RaisePropertyChanged("lLista_preco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> nDiasSemAtualicao {
            get {
                return this.nDiasSemAtualicaoField;
            }
            set {
                if ((this.nDiasSemAtualicaoField.Equals(value) != true)) {
                    this.nDiasSemAtualicaoField = value;
                    this.RaisePropertyChanged("nDiasSemAtualicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pAcressimoMaximo {
            get {
                return this.pAcressimoMaximoField;
            }
            set {
                if ((this.pAcressimoMaximoField.Equals(value) != true)) {
                    this.pAcressimoMaximoField = value;
                    this.RaisePropertyChanged("pAcressimoMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pDescontoMaximo {
            get {
                return this.pDescontoMaximoField;
            }
            set {
                if ((this.pDescontoMaximoField.Equals(value) != true)) {
                    this.pDescontoMaximoField = value;
                    this.RaisePropertyChanged("pDescontoMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> pPercentual {
            get {
                return this.pPercentualField;
            }
            set {
                if ((this.pPercentualField.Equals(value) != true)) {
                    this.pPercentualField = value;
                    this.RaisePropertyChanged("pPercentual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stAtualizacao {
            get {
                return this.stAtualizacaoField;
            }
            set {
                if ((this.stAtualizacaoField.Equals(value) != true)) {
                    this.stAtualizacaoField = value;
                    this.RaisePropertyChanged("stAtualizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte stContrato {
            get {
                return this.stContratoField;
            }
            set {
                if ((this.stContratoField.Equals(value) != true)) {
                    this.stContratoField = value;
                    this.RaisePropertyChanged("stContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xCodigoListaPreco {
            get {
                return this.xCodigoListaPrecoField;
            }
            set {
                if ((object.ReferenceEquals(this.xCodigoListaPrecoField, value) != true)) {
                    this.xCodigoListaPrecoField = value;
                    this.RaisePropertyChanged("xCodigoListaPreco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xLista {
            get {
                return this.xListaField;
            }
            set {
                if ((object.ReferenceEquals(this.xListaField, value) != true)) {
                    this.xListaField = value;
                    this.RaisePropertyChanged("xLista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xNrContrato {
            get {
                return this.xNrContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.xNrContratoField, value) != true)) {
                    this.xNrContratoField = value;
                    this.RaisePropertyChanged("xNrContrato");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PesquisaPadraoModelContract", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Components")]
    [System.SerializableAttribute()]
    public partial class PesquisaPadraoModelContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CHARACTER_MAXIMUM_LENGTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLUMN_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IS_NULLABLEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHARACTER_MAXIMUM_LENGTH {
            get {
                return this.CHARACTER_MAXIMUM_LENGTHField;
            }
            set {
                if ((this.CHARACTER_MAXIMUM_LENGTHField.Equals(value) != true)) {
                    this.CHARACTER_MAXIMUM_LENGTHField = value;
                    this.RaisePropertyChanged("CHARACTER_MAXIMUM_LENGTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLUMN_NAME {
            get {
                return this.COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COLUMN_NAMEField, value) != true)) {
                    this.COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("COLUMN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_TYPEField, value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IS_NULLABLE {
            get {
                return this.IS_NULLABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.IS_NULLABLEField, value) != true)) {
                    this.IS_NULLABLEField = value;
                    this.RaisePropertyChanged("IS_NULLABLE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="statusModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Resources.RecursosBases")]
    public enum statusModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nenhum = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        criado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        alterado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        excluido = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Lista_PrecoService.IserviceLista_Preco")]
    public interface IserviceLista_Preco {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/getLista_Preco", ReplyAction="http://tempuri.org/IserviceLista_Preco/getLista_PrecoResponse")]
        HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel getLista_Preco(int idListaPrecoPai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/getLista_Preco", ReplyAction="http://tempuri.org/IserviceLista_Preco/getLista_PrecoResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel> getLista_PrecoAsync(int idListaPrecoPai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/saveLista_Preco", ReplyAction="http://tempuri.org/IserviceLista_Preco/saveLista_PrecoResponse")]
        HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel saveLista_Preco(HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel objListaPreco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/saveLista_Preco", ReplyAction="http://tempuri.org/IserviceLista_Preco/saveLista_PrecoResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel> saveLista_PrecoAsync(HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel objListaPreco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/deleteLista_Preco", ReplyAction="http://tempuri.org/IserviceLista_Preco/deleteLista_PrecoResponse")]
        bool deleteLista_Preco(int idListaPrecoPai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/deleteLista_Preco", ReplyAction="http://tempuri.org/IserviceLista_Preco/deleteLista_PrecoResponse")]
        System.Threading.Tasks.Task<bool> deleteLista_PrecoAsync(int idListaPrecoPai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/copyLista_Preco", ReplyAction="http://tempuri.org/IserviceLista_Preco/copyLista_PrecoResponse")]
        int copyLista_Preco(HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel objListaPreco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/copyLista_Preco", ReplyAction="http://tempuri.org/IserviceLista_Preco/copyLista_PrecoResponse")]
        System.Threading.Tasks.Task<int> copyLista_PrecoAsync(HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel objListaPreco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/GetItensListaPreco", ReplyAction="http://tempuri.org/IserviceLista_Preco/GetItensListaPrecoResponse")]
        HLP.Comum.Facade.Lista_PrecoService.Lista_precoModel[] GetItensListaPreco(int idListaPrecoPai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceLista_Preco/GetItensListaPreco", ReplyAction="http://tempuri.org/IserviceLista_Preco/GetItensListaPrecoResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Facade.Lista_PrecoService.Lista_precoModel[]> GetItensListaPrecoAsync(int idListaPrecoPai);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IserviceLista_PrecoChannel : HLP.Comum.Facade.Lista_PrecoService.IserviceLista_Preco, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IserviceLista_PrecoClient : System.ServiceModel.ClientBase<HLP.Comum.Facade.Lista_PrecoService.IserviceLista_Preco>, HLP.Comum.Facade.Lista_PrecoService.IserviceLista_Preco {
        
        public IserviceLista_PrecoClient() {
        }
        
        public IserviceLista_PrecoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IserviceLista_PrecoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceLista_PrecoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceLista_PrecoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel getLista_Preco(int idListaPrecoPai) {
            return base.Channel.getLista_Preco(idListaPrecoPai);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel> getLista_PrecoAsync(int idListaPrecoPai) {
            return base.Channel.getLista_PrecoAsync(idListaPrecoPai);
        }
        
        public HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel saveLista_Preco(HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel objListaPreco) {
            return base.Channel.saveLista_Preco(objListaPreco);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel> saveLista_PrecoAsync(HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel objListaPreco) {
            return base.Channel.saveLista_PrecoAsync(objListaPreco);
        }
        
        public bool deleteLista_Preco(int idListaPrecoPai) {
            return base.Channel.deleteLista_Preco(idListaPrecoPai);
        }
        
        public System.Threading.Tasks.Task<bool> deleteLista_PrecoAsync(int idListaPrecoPai) {
            return base.Channel.deleteLista_PrecoAsync(idListaPrecoPai);
        }
        
        public int copyLista_Preco(HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel objListaPreco) {
            return base.Channel.copyLista_Preco(objListaPreco);
        }
        
        public System.Threading.Tasks.Task<int> copyLista_PrecoAsync(HLP.Comum.Facade.Lista_PrecoService.Lista_Preco_PaiModel objListaPreco) {
            return base.Channel.copyLista_PrecoAsync(objListaPreco);
        }
        
        public HLP.Comum.Facade.Lista_PrecoService.Lista_precoModel[] GetItensListaPreco(int idListaPrecoPai) {
            return base.Channel.GetItensListaPreco(idListaPrecoPai);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Facade.Lista_PrecoService.Lista_precoModel[]> GetItensListaPrecoAsync(int idListaPrecoPai) {
            return base.Channel.GetItensListaPrecoAsync(idListaPrecoPai);
        }
    }
}
