//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Entries.Services.wcf_PesquisaRapida {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf_PesquisaRapida.Iwcf_PesquisaRapida")]
    public interface Iwcf_PesquisaRapida {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_PesquisaRapida/GetValorDisplay", ReplyAction="http://tempuri.org/Iwcf_PesquisaRapida/GetValorDisplayResponse")]
        string GetValorDisplay(string _TableView, string[] _Items, string _FieldPesquisa, int idEmpresa, System.Nullable<int> _iValorPesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iwcf_PesquisaRapida/GetValorDisplay", ReplyAction="http://tempuri.org/Iwcf_PesquisaRapida/GetValorDisplayResponse")]
        System.Threading.Tasks.Task<string> GetValorDisplayAsync(string _TableView, string[] _Items, string _FieldPesquisa, int idEmpresa, System.Nullable<int> _iValorPesquisa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iwcf_PesquisaRapidaChannel : HLP.Entries.Services.wcf_PesquisaRapida.Iwcf_PesquisaRapida, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iwcf_PesquisaRapidaClient : System.ServiceModel.ClientBase<HLP.Entries.Services.wcf_PesquisaRapida.Iwcf_PesquisaRapida>, HLP.Entries.Services.wcf_PesquisaRapida.Iwcf_PesquisaRapida {
        
        public Iwcf_PesquisaRapidaClient() {
        }
        
        public Iwcf_PesquisaRapidaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iwcf_PesquisaRapidaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_PesquisaRapidaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_PesquisaRapidaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetValorDisplay(string _TableView, string[] _Items, string _FieldPesquisa, int idEmpresa, System.Nullable<int> _iValorPesquisa) {
            return base.Channel.GetValorDisplay(_TableView, _Items, _FieldPesquisa, idEmpresa, _iValorPesquisa);
        }
        
        public System.Threading.Tasks.Task<string> GetValorDisplayAsync(string _TableView, string[] _Items, string _FieldPesquisa, int idEmpresa, System.Nullable<int> _iValorPesquisa) {
            return base.Channel.GetValorDisplayAsync(_TableView, _Items, _FieldPesquisa, idEmpresa, _iValorPesquisa);
        }
    }
}
