//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Entries.ViewModel.tipoServicoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelBase", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HLP.Entries.Model.Models.Gerais.Tipo_servicoModel))]
    public partial class modelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Entries.ViewModel.tipoServicoService.PesquisaPadraoModelContract[] lcamposSqlNotNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HLP.Entries.ViewModel.tipoServicoService.statusModel statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Entries.ViewModel.tipoServicoService.PesquisaPadraoModelContract[] lcamposSqlNotNull {
            get {
                return this.lcamposSqlNotNullField;
            }
            set {
                if ((object.ReferenceEquals(this.lcamposSqlNotNullField, value) != true)) {
                    this.lcamposSqlNotNullField = value;
                    this.RaisePropertyChanged("lcamposSqlNotNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HLP.Entries.ViewModel.tipoServicoService.statusModel status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PesquisaPadraoModelContract", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Model.Components")]
    [System.SerializableAttribute()]
    public partial class PesquisaPadraoModelContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CHARACTER_MAXIMUM_LENGTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLUMN_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IS_NULLABLEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHARACTER_MAXIMUM_LENGTH {
            get {
                return this.CHARACTER_MAXIMUM_LENGTHField;
            }
            set {
                if ((this.CHARACTER_MAXIMUM_LENGTHField.Equals(value) != true)) {
                    this.CHARACTER_MAXIMUM_LENGTHField = value;
                    this.RaisePropertyChanged("CHARACTER_MAXIMUM_LENGTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLUMN_NAME {
            get {
                return this.COLUMN_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COLUMN_NAMEField, value) != true)) {
                    this.COLUMN_NAMEField = value;
                    this.RaisePropertyChanged("COLUMN_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_TYPE {
            get {
                return this.DATA_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_TYPEField, value) != true)) {
                    this.DATA_TYPEField = value;
                    this.RaisePropertyChanged("DATA_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IS_NULLABLE {
            get {
                return this.IS_NULLABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.IS_NULLABLEField, value) != true)) {
                    this.IS_NULLABLEField = value;
                    this.RaisePropertyChanged("IS_NULLABLE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="statusModel", Namespace="http://schemas.datacontract.org/2004/07/HLP.Comum.Resources.RecursosBases")]
    public enum statusModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nenhum = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        criado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        alterado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        excluido = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tipoServicoService.IserviceTipoServico")]
    public interface IserviceTipoServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceTipoServico/GetTipo", ReplyAction="http://tempuri.org/IserviceTipoServico/GetTipoResponse")]
        HLP.Entries.Model.Models.Gerais.Tipo_servicoModel GetTipo(int idTipoServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceTipoServico/GetTipo", ReplyAction="http://tempuri.org/IserviceTipoServico/GetTipoResponse")]
        System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Tipo_servicoModel> GetTipoAsync(int idTipoServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceTipoServico/Save", ReplyAction="http://tempuri.org/IserviceTipoServico/SaveResponse")]
        HLP.Entries.Model.Models.Gerais.Tipo_servicoModel Save(HLP.Entries.Model.Models.Gerais.Tipo_servicoModel tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceTipoServico/Save", ReplyAction="http://tempuri.org/IserviceTipoServico/SaveResponse")]
        System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Tipo_servicoModel> SaveAsync(HLP.Entries.Model.Models.Gerais.Tipo_servicoModel tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceTipoServico/Delete", ReplyAction="http://tempuri.org/IserviceTipoServico/DeleteResponse")]
        bool Delete(int idTipoServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceTipoServico/Delete", ReplyAction="http://tempuri.org/IserviceTipoServico/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int idTipoServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceTipoServico/Copy", ReplyAction="http://tempuri.org/IserviceTipoServico/CopyResponse")]
        int Copy(int idTipoServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IserviceTipoServico/Copy", ReplyAction="http://tempuri.org/IserviceTipoServico/CopyResponse")]
        System.Threading.Tasks.Task<int> CopyAsync(int idTipoServico);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IserviceTipoServicoChannel : HLP.Entries.ViewModel.tipoServicoService.IserviceTipoServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IserviceTipoServicoClient : System.ServiceModel.ClientBase<HLP.Entries.ViewModel.tipoServicoService.IserviceTipoServico>, HLP.Entries.ViewModel.tipoServicoService.IserviceTipoServico {
        
        public IserviceTipoServicoClient() {
        }
        
        public IserviceTipoServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IserviceTipoServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceTipoServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceTipoServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HLP.Entries.Model.Models.Gerais.Tipo_servicoModel GetTipo(int idTipoServico) {
            return base.Channel.GetTipo(idTipoServico);
        }
        
        public System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Tipo_servicoModel> GetTipoAsync(int idTipoServico) {
            return base.Channel.GetTipoAsync(idTipoServico);
        }
        
        public HLP.Entries.Model.Models.Gerais.Tipo_servicoModel Save(HLP.Entries.Model.Models.Gerais.Tipo_servicoModel tipo) {
            return base.Channel.Save(tipo);
        }
        
        public System.Threading.Tasks.Task<HLP.Entries.Model.Models.Gerais.Tipo_servicoModel> SaveAsync(HLP.Entries.Model.Models.Gerais.Tipo_servicoModel tipo) {
            return base.Channel.SaveAsync(tipo);
        }
        
        public bool Delete(int idTipoServico) {
            return base.Channel.Delete(idTipoServico);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int idTipoServico) {
            return base.Channel.DeleteAsync(idTipoServico);
        }
        
        public int Copy(int idTipoServico) {
            return base.Channel.Copy(idTipoServico);
        }
        
        public System.Threading.Tasks.Task<int> CopyAsync(int idTipoServico) {
            return base.Channel.CopyAsync(idTipoServico);
        }
    }
}
